
const config = {
		name: "chuilientuc",
		aliases: ["c"],
		version: "1.1.0",
		description: "Chửi liên tục người được tag",
		usage: "[tag]",
		cooldown: 3,
		permissions: [2],
		credits: "ngp"
}

if (!global.chuilientuc) {
		global.chuilientuc = new Map();
}

const DELAY_THREAD = 1000 * 60; // 1 phút chửi 1 lần/1 nhóm
const DELAY = 1900; // cứ mỗi 1 giây chửi 1 lần
const CAU_CHUI = [
    "sồn hăng lên con thú ê {name}",
"bem với cha mở đầu chó m ra nhe?🤣  {name}",
"sao mày thảm vãi lồn cần t lau nước mắt không!!!!=)))  {name}",
"mẹ mày bị tao địt rách màn trinh mà🤪  {name}",
"mẹ mày bị tao dã vào lồn=)))  {name}",
"địt mẹ mày sướng tê con cặc=)))  {name}",
"huhu nhìn mày như con cặc=)))  {name}",
"mày loạn luân bà già hả=)))  {name}",
"mẹ mày bị tao địt rên ư ử=)))  {name}",
"địt mẹ mày sảng khoái quá đi😛  {name}",
"tao địt mẹ mày nát lồn mà=)))  {name}",
"Ê bóng lồn  {name}",
"mẹ mày bị tao cưỡng hiếp=)))  {name}",
"mẹ mày đưa lồn chó liếm à🤣👈  {name}",
  "Sủa Mau Lên🤣",
  "Đĩ Mẹ Mày😅",
  "Óc Chó🤭?",
  "mày biết sợ rồi à 🤣🤣?",
  "mày cố nữa đi 😂?",
  "clm 🤣?",
  "sủa mau lên con chó🤣🤣",
  "con đĩ cave lộ lồn cay kiểu🤣🤣",
  "lũ ngu đòi đọ bot anh🤣👉",
  "kkk🤣🤣",
  "con đĩ cave show lồn show dú kiểu😜",
  "mày sợ anh à con đĩ😏?",
  "xạo à clm cuoii😏?",
  "sao m xạo da👉",
"cố đeee🤭",
"sồn hăng lên em🥺",
"sao m yếu v😔",
"cố tí nữa👉",
"sao kìa chậm à🙃",
"hăng hái lên tí chứ😤",
"tới sáng đi em ei=))",
"cố gắng tí eii🤑",
"k đc à:))",
"con eii cố de😗",
"sao m câm kì:))",
"gà j🤭",
"tnh gà=))",
"m gà mà🤨",
"dk à:)?",
"đúng mà ?",
"cãi à :))",
"mày còn gì khác hơn không :))",
"học lỏm kìa🤣",
"cố tí e ?",
"mếu à😭",
"sao mếu kìa:))",
"tao đã cho m mếu đâu :))",
"va lẹ lên chậm v😏?",
"sao kìa",
"từ bỏ r à",
"bị bạn bè bỏ rơi à 😏?",
"mạnh mẽ tí đi nà",
"cố đê con chó ăn cứt:))?",
":)))",
"sợ tao kìa🤣",
"sao sợ tao kìa",
"cay lắm phải kh",
"ớt rồi kìa em",
"mày còn chối à",
"làm tí đê",
"mới đó đã mệt r kìa",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
"ai cho m nhai",
"cay lắm r", 
"từ bỏ đi em",
"mày nghĩ mày làm t cay đc à",
"có đâu",
"tao đang hành m mà",
"bịa à",
"cay :)))))",
"cố eiii",
  "thằng bê đê bất lực vì mẹ nó bị đụ tung cái lồn:)))  {name}",
"con đĩ mẹ mày bất lực vì bị tao chửi mà chỉ biết câm lặng:)))  {name}",
"làm màu mà bị tao chửi rung cái con cặc:)))  {name}",
"Mẹ mày bị tao đụ lòi hột le:)))  {name}",
"thằng bê đê ảo cặc đòi cân và cái kết:)))  {name}",
"con đĩ mẹ của mày thèm cứt tao dữ lắm:)))  {name}",
"bị tao chửi sảng cặc đéo dám care:)))  {name}",
"mạnh lên sao yếu đuối v con:)))  {name}",
"mày run cặc chưa con:)))  {name}",
"chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))  {name}",
"chết cha nó sồn r  {name}",
"con đĩ mẹ mày gào thét đê?😛  {name}",
"mày gào lên con?😏  {name}",
"sao cay tao dọ?  {name}",
"mày sủa đi nè😛  {name}",
"sao mày xấu lồn gớm chó dị con?  {name}",
"sao cay tao hả😏?  {name}",
"sao mày giết mẹ vậy=)))  {name}",
"mày gào đi con=)))  {name}",
"nào ổn thì đú🤣👈  {name}",
"ê bê đê lên ăn hôi lẹ😘  {name}",
"mày đú rõ mò  {name}",
"sao mày ăn cứt tao😏  {name}",
"ai cho mày ăn cứt tao  {name}",
"sao mày óc cặc dữ con=)))  {name}",
"gặp tao đừng run nha?😂  {name}",
"con đĩ mẹ mày thèm cứt tao dữ lắm=)))  {name}",
"mày mồ côi mà đúng k🤣👈  {name}",
"ai cho mày sủa tao cho mày sủa chưa?  {name}",
"bị tao chọc cay hơn con chó luôn=)))  {name}",
"cố đi sắp win rồi nè😏  {name}",
"chừng nào mày mới làm lại tao dị?  {name}",
"mẹ mày sắp tắt thở kìa ê  {name}",
"đậu má mày gà mà sủa  {name}",
"sủa điên đi mà sủa hăng lên mới vui😘  {name}",
"mày mà ngưng một giây là con đĩ mẹ mày bả tắt đường thở á😏  {name}",
"ê chó ngu mày sợ tao hả😂  {name}",
"mày đú rõ mà sao mày đú dị?  {name}",
"mẹ mày chết chưa con=)))  {name}",
"ê bê đê sủa điên đi  {name}",
"sao mày sủa chậm dị?  {name}",
"nào làm lại tao nói đê?  {name}",
"bị tao chọc cay hơn con chó luôn😏  {name}",
"sủa đi rồi tao tha?  {name}",
"sủa điên lên cho mẹ?  {name}",
"mày ngưng là con đĩ mẹ mày chết?  {name}",
"cay tao lòi dái hả😏  {name}",
"não chó cay à?🤣  {name}",
"sao mày thảm dị=)))  {name}",
"mẹ mày bị tao địt rách màn trinh mà🤪  {name}",
"mẹ mày bị tao dã vào lồn=)))  {name}",
"địt mẹ mày sướng tê con cặc=)))  {name}",
"huhu nhìn mày như con cặc=)))  {name}",
"mày loạn luân bà già hả=)))  {name}",
"mẹ mày bị tao địt rên ư ử=)))  {name}",
"địt mẹ mày sảng khoái quá đi😛  {name}",
"tao địt mẹ mày nát lồn mà=)))  {name}",
"Ê bóng lồn  {name}",
"mẹ mày bị tao cưỡng hiếp=)))  {name}",
"mẹ mày đưa lồn chó liếm à🤣👈  {name}",
"mày óc cái lồn mà  {name}",
"năn nỉ đi tao tha😏  {name}",
"bú lồn tao đi🤪  {name}",
"mày ẳng gì dị?😏  {name}",
"nghe nói mày sợ tao?  {name}",
"thằng bê đê bất lực vì mẹ nó bị đụ tung cái lồn:)))  {name}",
"con đĩ mẹ mày bất lực vì bị tao chửi mà chỉ biết câm lặng:)))  {name}",
"làm màu mà bị tao chửi rung cái con cặc:)))  {name}",
"Mẹ mày bị tao đụ lòi hột le:)))  {name}",
"thằng bê đê ảo cặc đòi cân và cái kết:)))  {name}",
"con đĩ mẹ của mày thèm cứt tao dữ lắm:)))  {name}",
"bị tao chửi sảng cặc đéo dám care:)))  {name}",
"mạnh lên sao yếu đuối v con:)))  {name}",
"mày run cặc chưa con:)))  {name}",
"chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))  {name}",
"chết cha nó sồn r  {name}",
"con đĩ mẹ mày gào thét đê?😛  {name}",
"mày gào lên con?😏  {name}",
"sao cay tao dọ?  {name}",
"mày sủa đi nè😛  {name}",
"sao mày xấu lồn gớm chó dị con?  {name}",
"sao cay tao hả😏?  {name}",
"sao mày giết mẹ vậy=)))  {name}",
"mày gào đi con=)))  {name}",
"nào ổn thì đú🤣👈  {name}",
"ê bê đê lên ăn hôi lẹ😘  {name}",
"mày đú rõ mò  {name}",
"sao mày ăn cứt tao😏  {name}",
"ai cho mày ăn cứt tao  {name}",
"sao mày óc cặc dữ con=)))  {name}",
"gặp tao đừng run nha?😂  {name}",
"con đĩ mẹ mày thèm cứt tao dữ lắm=)))  {name}",
"mày mồ côi mà đúng k🤣👈  {name}",
"ai cho mày sủa tao cho mày sủa chưa?  {name}",
"bị tao chọc cay hơn con chó luôn=)))  {name}",
"cố đi sắp win rồi nè😏  {name}",
"chừng nào mày mới làm lại tao dị?  {name}",
"mẹ mày sắp tắt thở kìa ê  {name}",
"đậu má mày gà mà sủa  {name}",
  "cay {name}",
"kia {name}",
"c🤣👌{name}",
"oc {name}",
"cho {name}",
"di🤣🤣 {name}",
"me {name}",
"may {name}",
"ngu {name}",
"kia🐶 {name}",
"sao😏 {name}",
"yếu {name}",
"con{name}",
"on {name}",
"hong:))) {name}",
"🤣🤣 {name}",
"cay{name}",
"ko  {name}",
"cay tuột buồi 👉🤣{name}",
"ei ei =)) {name}",
"em {name}",
"chạy {name}",
"sợ 🤢🤢 {name}",
"kìa🤣🤣 👌{name}",
"bá{name}",
"dữ {name}",
"sua mau{name}",
"hú  {name}",
"kkk {name}",
"🤣🤣🐶 {name}",
"mau:)) {name}",
"đê :))) {name}",
"sủa mau=)) {name}",
":)) {name}",
"cố đi :3 {name}",
"sao:))) {name}",
"sua 🤣🤣 {name}",
"to 🤢🤢 {name}",
"len {name}",
" ui🤣🤣 {name}",
"kkk {name}",
"🤣🐶👌 {name}",
"oc 🤣🤣 {name}",
"kia {name}",
"may:)) {name}",
"đú :))) {name}",
"eo oyyy:3 {name}",
"cố {name}",
"lên)) {name}",
"cave 🤣🤣 {name}",
"mạnh lên:))) {name}",
"gõ loạn kìa {name}",
"thấy ngại ngùng z🤣🤘 {name}",
"tự nhiên đê {name}",
"mệt đk {name}",
"cấm m ngưng {name}",
"cay kia :))) {name}",
"lẹ đê:)) {name}",
"mày lag à :)) {name}",
"ngu:))) {name}",
"sua {name}",
"le {name}",
"con{name}",
"ey {name}",
"di{name}",
":))) {name}",
"me :))) {name}",
"may:))) {name}",
"sao chậm chạp v :)) {name}",
"óc 🤣🤣 {name}",
"lồn 🤣🤣 {name}",
"lên đê 🤣🤣 {name}",
"khựng dạ :))) {name}",
"t mạnh lắm à :))) {name}",
"chó ngu {name} ",
"bất ổn à 🤮🤮 {name}",
"run à {name}",
"chạy à  {name}",
"đuối à  {name}",
"bại chưa 👉😏 {name}",
"sủa mau🙄🙄👈 {name}",
  "Cha win à anh em😋🫰 {name}",
  " win r pp anh em🫰{name}",
  "cha trùm mxh {name}",
  "thằng bướm cay 🌶{name}",
"ớt cha lắm rồi đúng k {name}",
  "sủa cháy đê",
"sủa mạnh eei",
  "thẩm du cái lồn má m lên :))",
  "con đĩ cãi cùn",
  "địt bà nội sư gia nhà m =))",
  "úi úi",
  "nhanh lên con chó lồn khai khắm=))",
  "sao con đĩ mẹ ày gà vậy",
  "địt lồn mẹ mày",
  "dập cặc thằng cha mày liền",
  "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
  "Con thú đú",
  "lòi lồn chiến sĩ rồi à",
  "sao không mạnh mẽ lên",
  "khép lép vậy",
  "sợ hãi rồi à",
  "Lẹ lên con điếm thúi",
  "con đĩ mồ coi ăn hôi",
  "thế nào rồi",
  "sợ anh mày chưa",
  "anh mày bá sàn mà",
  "sao m chối hoài",
  "chối là con má m die",
  "ngu thì ngu vừa thôi=))",
  "không t đâm chết thằng cha mày",
  "óc chó dữ",
  "lồn mẹ mày",
  "điếm thúi ơi=))",
  "đừng rớt nhây nhó:3",
  "thấy sao rùi:3",
  "Bede sủa tiếng nghe choiw",
  "Cặc Cặc Cặc",
  "Lồn Lồn Lồn",
  "=))",
  "Thấy anh nhây bá ko",
  "quá bá mà",
  "sao lại anh được",
  "khép đuôi xin tha đê",
  "Rủa đĩ má m die",
  "Ngồi nhây tới đêm trăng tròn nè=))",
  "Nhây sao lại anh",
  "Bóng sida",
  "bede dập cu ơi=))",
  "nhắm chửi lại anh không=))",
  "lẹ lên con đĩ",
  "điếm thúi ăn hôi ơi:))",
  "Lên xem còn tài cán gì không nào",
  "Sao mà xạo lồn",
  "Dân va 2023 à",
  "Chỉ có vậy thôi sao",
  "mày làm được gì không😤",
  "hay chỉ biết phản kháng🤭=))",
  "tk cu bé phản kháng di😏?",
  "con đĩ cave luôn khảng phán đi🥺?",
  "bị chửi nên không phản kháng à😀?",
  "con cave và tk cu bé hợp nhề😏👉",
  "2 con bede không phản kháng được à😋",
  "2 con bede sợ anh rồi:))🙃",
  "chạy về mách mẹ à 2 con bede😗?",
  "chạy về trốn dô cái lồn mẹ mày đi😍?",
  "1 đứa bú lồn mẹ😎?",
  "1 đứa bú cu cha😎?",
  "bất hiếu cmnr:))😜",
  "mày làm gì để anh sợ đi:))🤣?",
  "mày có tý sát thương nào ko😂?",
  "con đĩ mẹ mày ăn cứt cố đi🤣?",
  "mày sợ anh à con chó ăn cứt:))?",
  "anh win cmnr clm🤣",
  "lũ cave cay cha cmnr😑",
  "cay anh  r à lũ đú😅",
  "sợ anh  à😗",
  "anh  win m mà:)))",
  "win mẹ rồi :)",
  "nào làm lại tao nói đê?  {name}",
"bị tao chọc cay hơn con chó luôn😏  {name}",
"sủa đi rồi tao tha?  {name}",
"sủa điên lên cho mẹ?  {name}",
"mày ngưng là con đĩ mẹ mày chết?  {name}",
"cay tao lòi dái hả😏  {name}",
"não chó cay à?🤣  {name}",
"sao mày thảm dị=)))  {name}",
"mẹ mày bị tao địt rách màn trinh mà🤪  {name}",
"mẹ mày bị tao dã vào lồn=)))  {name}",
"địt mẹ mày sướng tê con cặc=)))  {name}",
"huhu nhìn mày như con cặc=)))  {name}",
"mày loạn luân bà già hả=)))  {name}",
"mẹ mày bị tao địt rên ư ử=)))  {name}",
"địt mẹ mày sảng khoái quá đi😛  {name}",
"tao địt mẹ mày nát lồn mà=)))  {name}",
"Ê bóng lồn  {name}",
"mẹ mày bị tao cưỡng hiếp=)))  {name}",
"mẹ mày đưa lồn chó liếm à🤣👈  {name}",
"mày óc cái lồn mà  {name}",
"năn nỉ đi tao tha😏  {name}",
"bú lồn tao đi🤪  {name}",
"mày ẳng gì dị?😏  {name}",
"nghe nói mày sợ tao?  {name}",
"thằng bê đê bất lực vì mẹ nó bị đụ tung cái lồn:)))  {name}",
"con đĩ mẹ mày bất lực vì bị tao chửi mà chỉ biết câm lặng:)))  {name}",
"làm màu mà bị tao chửi rung cái con cặc:)))  {name}",
"Mẹ mày bị tao đụ lòi hột le:)))  {name}",
"thằng bê đê ảo cặc đòi cân và cái kết:)))  {name}",
"con đĩ mẹ của mày thèm cứt tao dữ lắm:)))  {name}",
"bị tao chửi sảng cặc đéo dám care:)))  {name}",
"mạnh lên sao yếu đuối v con:)))  {name}",
"mày run cặc chưa con:)))  {name}",
"chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))  {name}",
"chết cha nó sồn r  {name}",
"con đĩ mẹ mày gào thét đê?😛  {name}",
"mày gào lên con?😏  {name}",
"sao cay tao dọ?  {name}",
"mày sủa đi nè😛  {name}",
"sao mày xấu lồn gớm chó dị con?  {name}",
"sao cay tao hả😏?  {name}",
"sao mày giết mẹ vậy=)))  {name}",
"mày gào đi con=)))  {name}",
"nào ổn thì đú🤣👈  {name}",
"ê bê đê lên ăn hôi lẹ😘  {name}",
"mày đú rõ mò  {name}",
"sao mày ăn cứt tao😏  {name}",
"ai cho mày ăn cứt tao  {name}",
"sao mày óc cặc dữ con=)))  {name}",
"gặp tao đừng run nha?😂  {name}",
"con đĩ mẹ mày thèm cứt tao dữ lắm=)))  {name}",
"mày mồ côi mà đúng k🤣👈  {name}",
"ai cho mày sủa tao cho mày sủa chưa?  {name}",
"bị tao chọc cay hơn con chó luôn=)))  {name}",
"cố đi sắp win rồi nè😏  {name}",
"chừng nào mày mới làm lại tao dị?  {name}",
"mẹ mày sắp tắt thở kìa ê  {name}",
"đậu má mày gà mà sủa  {name}",
  "cay {name}",
"kia {name}",
"c🤣👌{name}",
"oc {name}",
"cho {name}",
"di🤣🤣 {name}",
"me {name}",
"may {name}",
"ngu {name}",
"kia🐶 {name}",
"sao😏 {name}",
"yếu {name}",
"con{name}",
"on {name}",
"hong:))) {name}",
"🤣🤣 {name}",
"cay{name}",
"ko  {name}",
"cay tuột buồi 👉🤣{name}",
"ei ei =)) {name}",
"em {name}",
"chạy {name}",
"sợ 🤢🤢 {name}",
"kìa🤣🤣 👌{name}",
"bá{name}",
"dữ {name}",
"sua mau{name}",
"hú  {name}",
"kkk {name}",
"🤣🤣🐶 {name}",
"mau:)) {name}",
"đê :))) {name}",
"sủa mau=)) {name}",
":)) {name}",
"cố đi :3 {name}",
"sao:))) {name}",
"sua 🤣🤣 {name}",
"to 🤢🤢 {name}",
"len {name}",
" ui🤣🤣 {name}",
"kkk {name}",
"🤣🐶👌 {name}",
"oc 🤣🤣 {name}",
"kia {name}",
"may:)) {name}",
"đú :))) {name}",
"eo oyyy:3 {name}",
"cố {name}",
"lên)) {name}",
"cave 🤣🤣 {name}",
"mạnh lên:))) {name}",
"gõ loạn kìa {name}",
"thấy ngại ngùng z🤣🤘 {name}",
"tự nhiên đê {name}",
"mệt đk {name}",
"cấm m ngưng {name}",
"cay kia :))) {name}",
"lẹ đê:)) {name}",
"mày lag à :)) {name}",
"ngu:))) {name}",
"sua {name}",
"le {name}",
"con{name}",
"ey {name}",
"di{name}",
":))) {name}",
"me :))) {name}",
"may:))) {name}",
"sao chậm chạp v :)) {name}",
"óc 🤣🤣 {name}",
"lồn 🤣🤣 {name}",
"lên đê 🤣🤣 {name}",
"khựng dạ :))) {name}",
"t mạnh lắm à :))) {name}",
"chó ngu {name} ",
"bất ổn à 🤮🤮 {name}",
"run à {name}",
"chạy à  {name}",
"đuối à  {name}",
"bại chưa 👉😏 {name}",
"sủa mau🙄🙄👈 {name}",
  "Cha win à anh em😋🫰 {name}",
  " win r pp anh em🫰{name}",
  "cha trùm mxh {name}",
  "thằng bướm cay 🌶{name}",
"ớt cha lắm rồi đúng k {name}",
  "sủa cháy đê",
"sủa mạnh eei",
  "thẩm du cái lồn má m lên :))",
  "con đĩ cãi cùn",
  "địt bà nội sư gia nhà m =))",
  "úi úi",
  "nhanh lên con chó lồn khai khắm=))",
  "sao con đĩ mẹ ày gà vậy",
  "địt lồn mẹ mày",
  "dập cặc thằng cha mày liền",
  "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
  "Con thú đú",
  "lòi lồn chiến sĩ rồi à",
  "sao không mạnh mẽ lên",
  "khép lép vậy",
  "sợ hãi rồi à",
  "Lẹ lên con điếm thúi",
  "con đĩ mồ coi ăn hôi",
  "thế nào rồi",
  "sợ anh mày chưa",
  "anh mày bá sàn mà",
  "sao m chối hoài",
  "chối là con má m die",
  "ngu thì ngu vừa thôi=))",
  "không t đâm chết thằng cha mày",
  "óc chó dữ",
  "lồn mẹ mày",
  "điếm thúi ơi=))",
  "đừng rớt nhây nhó:3",
  "thấy sao rùi:3",
  "Bede sủa tiếng nghe choiw",
  "Cặc Cặc Cặc",
  "Lồn Lồn Lồn",
  "=))",
  "Thấy anh nhây bá ko",
  "quá bá mà",
  "sao lại anh được",
  "khép đuôi xin tha đê",
  "Rủa đĩ má m die",
  "Ngồi nhây tới đêm trăng tròn nè=))",
  "Nhây sao lại anh",
  "Bóng sida",
  "bede dập cu ơi=))",
  "nhắm chửi lại anh không=))",
  "lẹ lên con đĩ",
  "điếm thúi ăn hôi ơi:))",
  "Lên xem còn tài cán gì không nào",
  "Sao mà xạo lồn",
  "Dân va 2023 à",
  "Chỉ có vậy thôi sao",
  "mày làm được gì không😤",
  "hay chỉ biết phản kháng🤭=))",
  "tk cu bé phản kháng di😏?",
  "con đĩ cave luôn khảng phán đi🥺?",
  "bị chửi nên không phản kháng à😀?",
  "con cave và tk cu bé hợp nhề😏👉",
  "2 con bede không phản kháng được à😋",
  "2 con bede sợ anh rồi:))🙃",
  "chạy về mách mẹ à 2 con bede😗?",
  "chạy về trốn dô cái lồn mẹ mày đi😍?",
  "1 đứa bú lồn mẹ😎?",
  "1 đứa bú cu cha😎?",
  "bất hiếu cmnr:))😜",
  "mày làm gì để anh sợ đi:))🤣?",
  "mày có tý sát thương nào ko😂?",
  "con đĩ mẹ mày ăn cứt cố đi🤣?",
  "mày sợ anh à con chó ăn cứt:))?",
  "anh win cmnr clm🤣",
  "lũ cave cay cha cmnr😑",
  "cay anh  r à lũ đú😅",
  "sợ anh  à😗",
  "anh  win m mà:)))",
  "cay {name}",
"kia {name}",
"c🤣👌{name}",
"oc {name}",
"cho {name}",
"di🤣🤣 {name}",
"me {name}",
"may {name}",
"ngu {name}",
"kia🐶 {name}",
"sao😏 {name}",
"yếu {name}",
"con{name}",
"on {name}",
"hong:))) {name}",
"🤣🤣 {name}",
"cay{name}",
"ko  {name}",
"cay tuột buồi 👉🤣{name}",
"ei ei =)) {name}",
"em {name}",
"chạy {name}",
"sợ 🤢🤢 {name}",
"kìa🤣🤣 👌{name}",
"bá{name}",
"dữ {name}",
"sua mau{name}",
"hú  {name}",
"kkk {name}",
"🤣🤣🐶 {name}",
"mau:)) {name}",
"đê :))) {name}",
"sủa mau=)) {name}",
":)) {name}",
"cố đi :3 {name}",
"sao:))) {name}",
"sua 🤣🤣 {name}",
"to 🤢🤢 {name}",
"len {name}",
" ui🤣🤣 {name}",
"kkk {name}",
"🤣🐶👌 {name}",
"oc 🤣🤣 {name}",
"kia {name}",
"may:)) {name}",
"đú :))) {name}",
"eo oyyy:3 {name}",
"cố {name}",
"lên)) {name}",
"cave 🤣🤣 {name}",
"mạnh lên:))) {name}",
"gõ loạn kìa {name}",
"thấy ngại ngùng z🤣🤘 {name}",
"tự nhiên đê {name}",
"mệt đk {name}",
"cấm m ngưng {name}",
"cay kia :))) {name}",
"lẹ đê:)) {name}",
"mày lag à :)) {name}",
"ngu:))) {name}",
"sua {name}",
"le {name}",
"con{name}",
"ey {name}",
"di{name}",
":))) {name}",
"me :))) {name}",
"may:))) {name}",
"sao chậm chạp v :)) {name}",
"óc 🤣🤣 {name}",
"lồn 🤣🤣 {name}",
"lên đê 🤣🤣 {name}",
"khựng dạ :))) {name}",
"t mạnh lắm à :))) {name}",
"chó ngu {name} ",
"bất ổn à 🤮🤮 {name}",
"run à {name}",
"chạy à  {name}",
"đuối à  {name}",
"bại chưa 👉😏 {name}",
"sủa mau🙄🙄👈 {name}",
  "Cha win à anh em😋🫰 {name}",
  " win r pp anh em🫰{name}",
  "cha trùm mxh {name}",
  "thằng bướm cay 🌶{name}",
"ớt cha lắm rồi đúng k {name}",
  "sủa cháy đê",
"sủa mạnh eei",
  "thẩm du cái lồn má m lên :))",
  "con đĩ cãi cùn",
  "địt bà nội sư gia nhà m =))",
  "úi úi",
  "nhanh lên con chó lồn khai khắm=))",
  "sao con đĩ mẹ ày gà vậy",
  "địt lồn mẹ mày",
  "dập cặc thằng cha mày liền",
  "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
  "Con thú đú",
  "lòi lồn chiến sĩ rồi à",
  "sao không mạnh mẽ lên",
  "khép lép vậy",
  "sợ hãi rồi à",
  "Lẹ lên con điếm thúi",
  "con đĩ mồ coi ăn hôi",
  "thế nào rồi",
  "sợ anh mày chưa",
  "anh mày bá sàn mà",
  "sao m chối hoài",
  "chối là con má m die",
  "ngu thì ngu vừa thôi=))",
  "không t đâm chết thằng cha mày",
  "óc chó dữ",
  "lồn mẹ mày",
  "điếm thúi ơi=))",
  "đừng rớt nhây nhó:3",
  "thấy sao rùi:3",
  "Bede sủa tiếng nghe choiw",
  "Cặc Cặc Cặc",
  "Lồn Lồn Lồn",
  "=))",
  "Thấy anh nhây bá ko",
  "quá bá mà",
  "sao lại anh được",
  "khép đuôi xin tha đê",
  "Rủa đĩ má m die",
  "Ngồi nhây tới đêm trăng tròn nè=))",
  "Nhây sao lại anh",
  "Bóng sida",
  "bede dập cu ơi=))",
  "nhắm chửi lại anh không=))",
  "lẹ lên con đĩ",
  "điếm thúi ăn hôi ơi:))",
  "Lên xem còn tài cán gì không nào",
  "Sao mà xạo lồn",
  "Dân va 2023 à",
  "Chỉ có vậy thôi sao",
  "mày làm được gì không😤",
  "hay chỉ biết phản kháng🤭=))",
  "tk cu bé phản kháng di😏?",
  "con đĩ cave luôn khảng phán đi🥺?",
  "bị chửi nên không phản kháng à😀?",
  "con cave và tk cu bé hợp nhề😏👉",
  "2 con bede không phản kháng được à😋",
  "2 con bede sợ anh rồi:))🙃",
  "chạy về mách mẹ à 2 con bede😗?",
  "chạy về trốn dô cái lồn mẹ mày đi😍?",
  "1 đứa bú lồn mẹ😎?",
  "1 đứa bú cu cha😎?",
  "bất hiếu cmnr:))😜",
  "mày làm gì để anh sợ đi:))🤣?",
  "mày có tý sát thương nào ko😂?",
  "con đĩ mẹ mày ăn cứt cố đi🤣?",
  "mày sợ anh à con chó ăn cứt:))?",
  "anh win cmnr clm🤣",
  "lũ cave cay cha cmnr😑",
  "cay anh  r à lũ đú😅",
  "sợ anh  à😗",
  "anh  win m mà:)))",
  "nào làm lại tao nói đê?  {name}",
"bị tao chọc cay hơn con chó luôn😏  {name}",
"sủa đi rồi tao tha?  {name}",
"sủa điên lên cho mẹ?  {name}",
"mày ngưng là con đĩ mẹ mày chết?  {name}",
"cay tao lòi dái hả😏  {name}",
"não chó cay à?🤣  {name}",
"sao mày thảm dị=)))  {name}",
"mẹ mày bị tao địt rách màn trinh mà🤪  {name}",
"mẹ mày bị tao dã vào lồn=)))  {name}",
"địt mẹ mày sướng tê con cặc=)))  {name}",
"huhu nhìn mày như con cặc=)))  {name}",
"mày loạn luân bà già hả=)))  {name}",
"mẹ mày bị tao địt rên ư ử=)))  {name}",
"địt mẹ mày sảng khoái quá đi😛  {name}",
"tao địt mẹ mày nát lồn mà=)))  {name}",
"Ê bóng lồn  {name}",
"mẹ mày bị tao cưỡng hiếp=)))  {name}",
"mẹ mày đưa lồn chó liếm à🤣👈  {name}",
"mày óc cái lồn mà  {name}",
"năn nỉ đi tao tha😏  {name}",
"bú lồn tao đi🤪  {name}",
"mày ẳng gì dị?😏  {name}",
"nghe nói mày sợ tao?  {name}",
"thằng bê đê bất lực vì mẹ nó bị đụ tung cái lồn:)))  {name}",
"con đĩ mẹ mày bất lực vì bị tao chửi mà chỉ biết câm lặng:)))  {name}",
"làm màu mà bị tao chửi rung cái con cặc:)))  {name}",
"Mẹ mày bị tao đụ lòi hột le:)))  {name}",
"thằng bê đê ảo cặc đòi cân và cái kết:)))  {name}",
"con đĩ mẹ của mày thèm cứt tao dữ lắm:)))  {name}",
"bị tao chửi sảng cặc đéo dám care:)))  {name}",
"mạnh lên sao yếu đuối v con:)))  {name}",
"mày run cặc chưa con:)))  {name}",
"chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))  {name}",
"chết cha nó sồn r  {name}",
"con đĩ mẹ mày gào thét đê?😛  {name}",
"mày gào lên con?😏  {name}",
"sao cay tao dọ?  {name}",
"mày sủa đi nè😛  {name}",
"sao mày xấu lồn gớm chó dị con?  {name}",
"sao cay tao hả😏?  {name}",
"sao mày giết mẹ vậy=)))  {name}",
"mày gào đi con=)))  {name}",
"nào ổn thì đú🤣👈  {name}",
"ê bê đê lên ăn hôi lẹ😘  {name}",
"mày đú rõ mò  {name}",
"sao mày ăn cứt tao😏  {name}",
"ai cho mày ăn cứt tao  {name}",
"sao mày óc cặc dữ con=)))  {name}",
"gặp tao đừng run nha?😂  {name}",
"con đĩ mẹ mày thèm cứt tao dữ lắm=)))  {name}",
"mày mồ côi mà đúng k🤣👈  {name}",
"ai cho mày sủa tao cho mày sủa chưa?  {name}",
"bị tao chọc cay hơn con chó luôn=)))  {name}",
"cố đi sắp win rồi nè😏  {name}",
"chừng nào mày mới làm lại tao dị?  {name}",
"mẹ mày sắp tắt thở kìa ê  {name}",
"đậu má mày gà mà sủa  {name}",
  "cay {name}",
"kia {name}",
"c🤣👌{name}",
"oc {name}",
"cho {name}",
"di🤣🤣 {name}",
"me {name}",
"may {name}",
"ngu {name}",
"kia🐶 {name}",
"sao😏 {name}",
"yếu {name}",
"con{name}",
"on {name}",
"hong:))) {name}",
"🤣🤣 {name}",
"cay{name}",
"ko  {name}",
"cay tuột buồi 👉🤣{name}",
"ei ei =)) {name}",
"em {name}",
"chạy {name}",
"sợ 🤢🤢 {name}",
"kìa🤣🤣 👌{name}",
"bá{name}",
"dữ {name}",
"sua mau{name}",
"hú  {name}",
"kkk {name}",
"🤣🤣🐶 {name}",
"mau:)) {name}",
"đê :))) {name}",
"sủa mau=)) {name}",
":)) {name}",
"cố đi :3 {name}",
"sao:))) {name}",
"sua 🤣🤣 {name}",
"to 🤢🤢 {name}",
"len {name}",
" ui🤣🤣 {name}",
"kkk {name}",
"🤣🐶👌 {name}",
"oc 🤣🤣 {name}",
"kia {name}",
"may:)) {name}",
"đú :))) {name}",
"eo oyyy:3 {name}",
"cố {name}",
"lên)) {name}",
"cave 🤣🤣 {name}",
"mạnh lên:))) {name}",
"gõ loạn kìa {name}",
"thấy ngại ngùng z🤣🤘 {name}",
"tự nhiên đê {name}",
"mệt đk {name}",
"cấm m ngưng {name}",
"cay kia :))) {name}",
"lẹ đê:)) {name}",
"mày lag à :)) {name}",
"ngu:))) {name}",
"sua {name}",
"le {name}",
"con{name}",
"ey {name}",
"di{name}",
":))) {name}",
"me :))) {name}",
"may:))) {name}",
"sao chậm chạp v :)) {name}",
"óc 🤣🤣 {name}",
"lồn 🤣🤣 {name}",
"lên đê 🤣🤣 {name}",
"khựng dạ :))) {name}",
"t mạnh lắm à :))) {name}",
"chó ngu {name} ",
"bất ổn à 🤮🤮 {name}",
"run à {name}",
"chạy à  {name}",
"đuối à  {name}",
"bại chưa 👉😏 {name}",
"sủa mau🙄🙄👈 {name}",
  "Cha win à anh em😋🫰 {name}",
  " win r pp anh em🫰{name}",
  "cha trùm mxh {name}",
  "thằng bướm cay 🌶{name}",
"ớt cha lắm rồi đúng k {name}",
  "sủa cháy đê {name}",
"sủa mạnh eei",
  "thẩm du cái lồn má m lên :))",
  "con đĩ cãi cùn",
  "địt bà nội sư gia nhà m =))",
  "úi úi",
  "nhanh lên con chó lồn khai khắm=))",
  "sao con đĩ mẹ ày gà vậy",
  "địt lồn mẹ mày",
  "dập cặc thằng cha mày liền",
  "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
  "Con thú đú",
  "lòi lồn chiến sĩ rồi à",
  "sao không mạnh mẽ lên",
  "khép lép vậy",
  "sợ hãi rồi à",
  "Lẹ lên con điếm thúi",
  "con đĩ mồ coi ăn hôi",
  "thế nào rồi",
  "sợ anh mày chưa",
  "anh mày bá sàn mà",
  "sao m chối hoài",
  "chối là con má m die",
  "ngu thì ngu vừa thôi=))",
  "không t đâm chết thằng cha mày",
  "óc chó dữ",
  "lồn mẹ mày",
  "điếm thúi ơi=))",
  "đừng rớt nhây nhó:3",
  "thấy sao rùi:3",
  "Bede sủa tiếng nghe choiw",
  "Cặc Cặc Cặc",
  "Lồn Lồn Lồn",
  "=))",
  "Thấy anh nhây bá ko",
  "quá bá mà",
  "sao lại anh được",
  "khép đuôi xin tha đê",
  "Rủa đĩ má m die",
  "Ngồi nhây tới đêm trăng tròn nè=))",
  "Nhây sao lại anh",
  "Bóng sida",
  "bede dập cu ơi=))",
  "nhắm chửi lại anh không=))",
  "lẹ lên con đĩ",
  "điếm thúi ăn hôi ơi:))",
  "Lên xem còn tài cán gì không nào",
  "Sao mà xạo lồn",
  "Dân va 2023 à",
  "Chỉ có vậy thôi sao",
  "mày làm được gì không😤",
  "hay chỉ biết phản kháng🤭=))",
  "tk cu bé phản kháng di😏?",
  "con đĩ cave luôn khảng phán đi🥺?",
  "bị chửi nên không phản kháng à😀?",
  "con cave và tk cu bé hợp nhề😏👉",
  "2 con bede không phản kháng được à😋",
  "2 con bede sợ anh rồi:))🙃",
  "chạy về mách mẹ à 2 con bede😗?",
  "chạy về trốn dô cái lồn mẹ mày đi😍?",
  "1 đứa bú lồn mẹ😎?",
  "1 đứa bú cu cha😎?",
  "bất hiếu cmnr:))😜",
  "mày làm gì để anh sợ đi:))🤣?",
  "mày có tý sát thương nào ko😂?",
  "con đĩ mẹ mày ăn cứt cố đi🤣?",
  "mày sợ anh à con chó ăn cứt:))?",
  "anh win cmnr clm🤣",
  "lũ cave cay cha cmnr😑",
  "cay anh  r à lũ đú😅",
"hăng tiếp đi",
"tới sáng k em",
"ko tới sáng à",
"chán v",
"m gà vậy :))",
"sao ngu dậy con:))",
"coi tụi nó dồn ngu kìa",
"sao mày ngu dậy:))?",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"sao mới nhiêu đó đã đuối r à:))?",
"yếu đến thế à",
"sao kìa",
"khóc kìa",
"cầu cứu lẹ ei",
"ai cứu đc m à :))",
"tao bá mà",
"sao m gà thế",
"hăng lẹ cho tao",
"con chó eiii🤣",
"ổn k em",
"kh ổn r à",
"xin tha eii",
"mẹ mày ngu à",
"bú cặc cha m k em",
"thg giả gái :))",
"coi nó ngu kìa ae",
"con chó này giả ngu à",
"m ổn k",
"mồ côi kìa",
"sao v sợ r à",
"cố gắng tí em",
"cay cú lắm r",
"đấy đấy bắt đầu",
"chảy nước đái bò r à em",
"sao kìa đừng run",
"mày run à:))",
"thg dái lở",
"cay mẹ m lắm",
"lgbt xuất trận ae eii",
"thg cặc giết cha mắng mẹ",
"sủa mạnh đê",
"mày chết r à:))",
"sao chết kìa",
"bị t hành nên muốn chết à🤣🤣",
"con lồn ngu=))",
"sao kìa",
"mạnh lên kìa",
"yếu sinh lý à",
  "sủa đê",
"cay à",
"hăng đê",
"gà kìa ae",
"akakaa",
"óc chó kìa",
"🤣🤣🤣",
"ổn không🤣🤣",
"bất ổn à",
"ơ kìaaa",
"sao lại chạy vậy😏?",
"hăng hái đê",
"chạy à 🤣🤣",
"tởn à",
"kkkk",
"mày dốt à",
"cặc ngu",
"cháy đê",
"chat hăng lên",
"cố lên",
"mồ côi cay",
"cay à",
"cn chó ngu",
"óc cặc kìa",
"đĩ đú:))",
"đú kìa",
"cùn v",
"r x",
"hhhhh",
"kkakak",
"sao đú",
"cặc con",
"ngu kìa",
"chat mạnh đê",
"hăng ee",
"ơ ơ ơ",
"sủa cháy đê",
"sủa mạnh eei",
  "thẩm du cái lồn má m lên :))",
  "con đĩ cãi cùn",
  "địt bà nội sư gia nhà m =))",
  "úi úi",
  "nhanh lên con chó lồn khai khắm=))",
  "sao con đĩ mẹ ày gà vậy",
  "địt lồn mẹ mày",
  "dập cặc thằng cha mày liền",
  "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
  "Con thú đú",
  "lòi lồn chiến sĩ rồi à",
  "sao không mạnh mẽ lên",
  "khép lép vậy",
  "sợ hãi rồi à",
  "Lẹ lên con điếm thúi",
  "con đĩ mồ coi ăn hôi",
  "thế nào rồi",
  "sợ anh mày chưa",
  "anh mày bá sàn mà",
  "sao m chối hoài",
  "chối là con má m die",
  "ngu thì ngu vừa thôi=))",
  "không t đâm chết thằng cha mày",
  "óc chó dữ",
  "lồn mẹ mày",
  "điếm thúi ơi=))",
  "đừng rớt nhây nhó:3",
  "thấy sao rùi:3",
  "Bede sủa tiếng nghe choiw",
  "Cặc Cặc Cặc",
  "Lồn Lồn Lồn",
  "=))",
  "Thấy anh nhây bá ko",
  "quá bá mà",
  "sao lại anh được",
  "khép đuôi xin tha đê",
  "Rủa đĩ má m die",
  "Ngồi nhây tới đêm trăng tròn nè=))",
  "Nhây sao lại anh",
  "Bóng sida",
  "bede dập cu ơi=))",
  "nhắm chửi lại anh không=))",
  "lẹ lên con đĩ",
  "điếm thúi ăn hôi ơi:))",
  "Lên xem còn tài cán gì không nào",
  "Sao mà xạo lồn",
  "Dân va 2023 à",
  "Chỉ có vậy thôi à",
  "mày làm được gì không😤",
  "hay chỉ biết phản kháng🤭=))",
  "tk cu bé phản kháng di😏?",
  "con đĩ cave luôn khảng phán đi",
  "bị chửi nên không phản kháng à",
  "con cave và tk cu bé hợp nhề😏",
  "con bede không phản kháng được à",
  "con bede sợ anh rồi:)",
  "chạy về mách mẹ à con bede",
  "chạy về trốn dô cái lồn mẹ mày đi?",
  "1 đứa bú lồn mẹ",
  "1 đứa bú cu cha",
  "bất hiếu cmnr:))",
  "mày làm gì để anh sợ đi:))",
  "mày có tý sát thương nào ko",
  "con đĩ mẹ mày ăn cứt cố đi",
  "mày sợ anh à con chó ăn cứt:))?",
  "anh win cmnr clm",
  "lũ cave cay cha cmnr",
  "cay anh  r à lũ đú",
  "sợ anh  à",
  "anh  win m mà:)))",
  "win nha clm bede🤣🤣",
	"chó ăn cứt cay 🤣🤣 {name}",
"sủa đê 🤣🤣 {name}",
"chó bú cứt🤣🤣👌{name}",
"hăng hái đê :)) {name}",
"chậm dọ 🤣🤣 {name}",
"óc dái cay r🤣🤣 {name}",
"ăn hại phát biểu lẹ đê 🤣🤣 {name}",
"óc dái :))) {name}",
"ổn phải k? {name}",
"ngu ớn 🤣🤣👌 {name}",
"chó ăn cứt 🐶 {name}",
"dái đú :)))) {name}",
"yếu dữ ta😏😏 {name}",
"con chó đần👉🤣 {name}",
"ổn dữ chưa =))) {name}",
  	"clm kkk sủa đê {name}",
"sủa đê 🤣🤣 {name}",
"chó bú cứt🤣🤣👌{name}",
"hăng hái đê :)) {name}",
"chậm dọ 🤣🤣 {name}",
"óc chó cay r🤣🤣 {name}",
"ăn hại phát biểu lẹ đê 🤣🤣 {name}",
"óc chó :))) {name}",
"ổn phải k? {name}",
"ngu ớn 🤣🤣👌 {name}",
"chó ăn cứt 🐶 {name}",
"đĩ mẹ mày ăn cứt sao ngu vậy😏 {name}",
"yếu dữ ta😏😏 {name}",
"con chó đần👉🤣 {name}",
"ổn dữ chưa =))) {name}",
"run ớn dạ :))) {name}",
"óc đú cay cmnr 🤣🤣 {name}",
"rồi xong 🤢🤢 {name}",
"có thể hăng ko á  {name}",
"ẻm cay doài =))) {name}",
"cay tuột buồi 👉🤣{name}",
"ei ei =)) {name}",
"em ei :3 {name}",
"chạy à {name}",
"mày sợ hả 🤢🤢 {name}",
"coi ẻm sồn kìa🤣🤣 👌{name}",
"lại bá à :))) {name}",
"sao chậm dữ {name}",
"eo oyyy:3 {name}",
"hú hú🤨 {name}",
"sao ức chế dạ 😏😏 {name}",
"con não cún bị chửi kìa 🤣🤣🐶 {name}",
"mau đê :)) {name}",
"hăng đê :))) {name}",
"sủa mau đê =)) {name}",
"cần cứu ko :)) {name}",
"cố đi :3 {name}",
"gáng lên đê :))) {name}",
"sủa to lên🤣🤣 {name}",
"phò nông thôn 🤢🤢 {name}",
"óc cặc tỉnh lẽ =)))) {name}",
"khoẻ ko 🤣🤣 {name}",
"kkk {name}",
"đói à🤣🐶👌 {name}",
"ăn chưa à 🤣🤣 {name}",
"chưa đk :))) {name}",
"thấy kém cõi :)) {name}",
"đú cứt kìa :))) {name}",
"eo oyyy:3 {name}",
"cố đê 🤣🤣 {name}",
"thấy mày đơ đơ :))) {name}",
"con cave 🤣🤣 {name}",
"mạnh lên:))) {name}",
"gõ mạnh lên đê:)) {name}",
"thấy ngại ngùng z🤣🤘 {name}",
"tự nhiên đê {name}",
"mệt đk {name}",
"cấm m ngưng {name}",
"đĩ đầu đinh :))) {name}",
"lẹ đê:)) {name}",
"mày lag à :)) {name}",
"m trầm cảm à :))) {name}",
"tâm lí ko vững à :)) {name}",
"cần thuốc à :)) {name}",
"hấp hối hả🤣🤣 {name}",
"khó thở dk :)) {name}",
"cần oxi ko :))) {name}",
"mày bệnh nặng lắm à :))) {name}",
"tuột hứng cha :))) {name}",
"tnh gà :))) {name}",
"sao chậm chạp v :)) {name}",
"óc dái 🤣🤣 {name}",
"lồn cụ con đĩ đớ🤣🤣 {name}",
"lưu loát lên đê 🤣🤣 {name}",
"khựng dạ :))) {name}",
"t mạnh lắm phải ko à :))) {name}",
":))) nhỏ mếu à ae {name}",
"m nghèo mà {name}",
"sợ t lắm à:3 {name}",
"hả cu =))) {name}",
"thấy tội quá:)) {name}",
"thương ẻm cố gắng🤢🤘 {name}",
"mà ngu🤣🤣 {name}",
":)) 🤣🤣 {name}",
"cay lắm à :)) {name}",
"nhạt nhoè v à {name}",
"ko cảm hứng để hăng à :))) {name}",
"xạo lồn à :))) {name}",
"khóc đk :))) {name}",
"cave tỉnh lẽ phát biểu:)) {name}",
"ra tín hiệu đê :))) {name}",
"SOS con dái đú 🤣🤣🤢 {name}",
"ớ ớ ớ :))) {name}",
"chó ăn cứt :))) {name}",
"chó đú sàn 👌🐶 {name}",
"ỉa ra máu r à :))) {name}",
"nghèo k có nghi lực à:)) {name}",
"phản kháng đê :))) t win à {name}",
"kkk {name}",
"m chết r à :))) {name}",
"m nghèo mà em 😏🤣 {name}",
"m thèm cứt t mà:)) {name}",
"đĩ mẹ m ngu mà👉🤣 {name}",
"m cay tao mà :)) {name}",
"con óc cứt thối🤢🤢 {name}",
"con đĩ mặt chim🤪🤪 {name}",
"ôm hận à 🤨 {name}",
"con đĩ nhà núi :))) {name}",
"bede bóng lộ =)) {name}",
"cn đĩ mẹ mày {name}",
"tao từ hình mẹ m mà :)) {name}",
"tk phế vật ăn hại😏🤘 {name}",
"đú đởn hả con :)) {name}",
"m sao dọ {name}",
"sủa nè  {name}",
"123 sủa😏 {name}",
"lẹ nè  {name}",
"alo alo hú hú  {name}",
"th cầm thú {name}",
"m s dạ  {name}",
"m sợ mẹ hả  {name}",
"lên đi mẹ ko giết cha má m đâu mà 😏 {name}",
"hù :)) {name}",
"bất ổn hở {name}",
"s đó  {name}",
"m rớt kìa th gà🤪 {name}",
"t cấm m chối nhen {name}",
"chối t giết cha má m nè:))) {name}",
"hăng xíu lẹ kaka🤢 {name}",
"th đần  {name}",
"lên mẹ biểu {name}",
"k lên t tuyệt chủng m nhen cn thú {name}",
"m thích đú ko dạ🤨 {name}",
"ko rep = t win nhen  {name}",
"cấm chạy nhen {name}",
"m mau  {name}",
"lên đây ơ ơ  {name}",
"th ngu ê {name}",
"s á lên đây mẹ sút m chết {name}",
"m khóc à 👉🤣 {name}",
"sủa liên tục ơ🤣🤣 {name}",
"cầu cứu lũ đú à  {name}",
"sục dái nó xem à {name}",
"dái thâm v? {name}",
"chậm v cn culi🤣🤣👌 {name}",
"hoảng loạn à {name}",
"bất ổn à 🤮🤮 {name}",
"run à {name}",
"chạy à  {name}",
"đuối à  {name}",
"bại chưa 👉😏 {name}",
"sủa mau🙄🙄👈 {name}",
"mạnh dạn lên  {name}",
"nhanh t cho cơ hội cứu má m nè {name}",
"cấm mách mẹ {name}",
"ảo war hở :)) {name}",
"dồn ko  {name}",
"đua nè lên sàn t chấp😏👌 {name}",
"th chợ búa m sao v {name}",
"th đầu buồi mặt chó😢🫵🏻👈🏻 {name}",
"cấm hoảng loạn {name}",
"lại phải win nữa à🙄🙄 {name}",
"kkk {name}",
  "phế nhân thế à {name}",
  "Thằng bede miền núi {name}",
  "thằng óc chó tật nguyền=)) {name}",
  "bú lồn đĩ mẹ mày die rồi à :)) {name}",
  "tiểu tốt vô danh vậy {name} =))",
  "{name} ngu mặt mâm :))",
  "{name} bê đê miền múi heo nái xổng chuồng 😏",
  "{name} ơ thế sao mày không sủa tiếp à😏👌",
  "{name} buồn cho thằng cha mày có đứa con dị dạng=))",
  "{name} mặt cặc sủa lồn đĩ mẹ mày đi ơ 😏",
  "{name} Cay mẹ mày à",
  "{name} Sao cay vậy",
  "{name} Sủa lẹ lên:3",
  "{name} Ước cay :))",
  "{name} Con béo =))",
  "{name}Sao mày mập vậy",
  "{name} 100kí à 😏👌",
  "{name} Eo ôi",
  "{name} Sủa lẹ",
  "{name} Con đĩ =))",
  "{name} Ai cho m câm vậy 😏",
  "{name} Đuối rồi à :))",
  "{name} Mạnh mẽ lên👉🤣👉",
  "{name} Đừng bê đê bóng gồng nữa nữa :))",
  "{name} Đứng dạy phản kháng mau",
  "{name} Lẹ lên",
  "{name} Lật ngược tình thế đê",
  "{name} Đụ má mày gà v con chó",
  "{name} Bị tao chửi cho khóc rồi à",
  "{name} Đĩ mẹ m🤣🤣🤣",
  "{name} Khóc r sao",
  "{name} câm coi con thú",
  "{name} biết quỳ gối van tha chưa =))",
  "{name} mặt dái bú dái th cha mày r à",
  "{name} ớ sủa nào",
  "{name} tìm thằng phế nhân cầu cứu à",
  "{name} Bê đê đi cầu cứu bạn bè à=))",
  "{name} con đĩ tật nguyền không bạn bè kìa",
  "{name} sao không có tiền zọ",
  "{name} chắc sài tiền âm phủ phớ hơm =))",
  "{name} mẹ mày đi làm điếm rồi kìa",
  "{name} cha mày đi bán vé số phải không:))",
  "{name} bà già mày lên cơn hen xuyễn đột tử=))",
  "{name} nghèo nàn từ ngữ vậy sao=))",
  "{name} hay không có học thức",
  "{name} mới lên lớp một hay sao mà sủa ko rõ",
  "{name} thế là mày thiểu năng chậm phát triển à",
  "{name} thế mày bú lồn",
  "{name} con mẹ mẹ mày nhiều quá hay sao",
  "{name} phế vật đến tận cùng =))",
  "{name} ngu thì cho người ta ngu với",
  "{name} chứ con đĩ má mày ngu quá ko thấy nhục à",
  "{name} cắt dái làm thái giám đko thằng ngu=))",
  "{name} Bede mà giấu là sao??",
  "{name} Thế nào mới hết bị Sida thằng mặt cặc",
  "{name} Rủa chết con đĩ má mày còn được nò:3",
  "{name} thế heo nái đẻ mấy nứa rồi",
  "{name} Mà trông zú xệ thế con đĩ=))",
  "{name} đụ banh cái lồn má m rồi hay gì",
  "{name} sợ chưa=))",
  "con đĩ ăn cứt sợ rồi à =))😏🔪 {name}",
  "mày sợ anh rồi Kìa 😱 😜 {name}",
  "anh  bá vãi ò m sợ à😏👉 {name}",
  "thdat win à anh em😋🫰 {name}",
  "dthe win r pp anh em🫰{name}",
  "cay {name}",
"kia {name}",
"c🤣👌{name}",
"oc {name}",
"cho {name}",
"di🤣🤣 {name}",
"me {name}",
"may {name}",
"ngu {name}",
"kia🐶 {name}",
"sao😏 {name}",
"yếu {name}",
"con{name}",
"on {name}",
"hong:))) {name}",
"🤣🤣 {name}",
"cay{name}",
"ko  {name}",
"cay tuột buồi 👉🤣{name}",
"ei ei =)) {name}",
"em {name}",
"chạy {name}",
"sợ 🤢🤢 {name}",
"kìa🤣🤣 👌{name}",
"bá{name}",
"dữ {name}",
"sua mau{name}",
"hú  {name}",
"kkk {name}",
"🤣🤣🐶 {name}",
"mau:)) {name}",
"đê :))) {name}",
"sủa mau=)) {name}",
":)) {name}",
"cố đi :3 {name}",
"sao:))) {name}",
"sua 🤣🤣 {name}",
"to 🤢🤢 {name}",
"len {name}",
" ui🤣🤣 {name}",
"kkk {name}",
"🤣🐶👌 {name}",
"oc 🤣🤣 {name}",
"kia {name}",
"may:)) {name}",
"đú :))) {name}",
"eo oyyy:3 {name}",
"cố {name}",
"lên)) {name}",
"cave 🤣🤣 {name}",
"mạnh lên:))) {name}",
"gõ loạn kìa {name}",
"thấy ngại ngùng z🤣🤘 {name}",
"tự nhiên đê {name}",
"mệt đk {name}",
"cấm m ngưng {name}",
"cay kia :))) {name}",
"lẹ đê:)) {name}",
"mày lag à :)) {name}",
"ngu:))) {name}",
"sua {name}",
"le {name}",
"con{name}",
"ey {name}",
"thằng bê đê bất lực vì mẹ nó bị đụ tung cái lồn:)))  {name}",
"con đĩ mẹ mày bất lực vì bị tao chửi mà chỉ biết câm lặng:)))  {name}",
"làm màu mà bị tao chửi rung cái con cặc:)))  {name}",
"Mẹ mày bị tao đụ lòi hột le:)))  {name}",
"thằng bê đê ảo cặc đòi cân và cái kết:)))  {name}",
"con đĩ mẹ của mày thèm cứt tao dữ lắm:)))  {name}",
"bị tao chửi sảng cặc đéo dám care:)))  {name}",
"mạnh lên sao yếu đuối v con:)))  {name}",
"mày run cặc chưa con:)))  {name}",
"chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))  {name}",
"chết cha nó sồn r  {name}",
"con đĩ mẹ mày gào thét đê?😛  {name}",
"mày gào lên con?😏  {name}",
"sao cay tao dọ?  {name}",
"mày sủa đi nè😛  {name}",
"sao mày xấu lồn gớm chó dị con?  {name}",
"sao cay tao hả😏?  {name}",
"sao mày giết mẹ vậy=)))  {name}",
"mày gào đi con=)))  {name}",
"nào ổn thì đú🤣👈  {name}",
"ê bê đê lên ăn hôi lẹ😘  {name}",
"mày đú rõ mò  {name}",
"sao mày ăn cứt tao😏  {name}",
"ai cho mày ăn cứt tao  {name}",
"sao mày óc cặc dữ con=)))  {name}",
"gặp tao đừng run nha?😂  {name}",
"con đĩ mẹ mày thèm cứt tao dữ lắm=)))  {name}",
"mày mồ côi mà đúng k🤣👈  {name}",
"ai cho mày sủa tao cho mày sủa chưa?  {name}",
"bị tao chọc cay hơn con chó luôn=)))  {name}",
"cố đi sắp win rồi nè😏  {name}",
"chừng nào mày mới làm lại tao dị?  {name}",
"mẹ mày sắp tắt thở kìa ê  {name}",
"đậu má mày gà mà sủa  {name}",
"sủa điên đi mà sủa hăng lên mới vui😘  {name}",
"mày mà ngưng một giây là con đĩ mẹ mày bả tắt đường thở á😏  {name}",
"ê chó ngu mày sợ tao hả😂  {name}",
"mày đú rõ mà sao mày đú dị?  {name}",
"mẹ mày chết chưa con=)))  {name}",
"ê bê đê sủa điên đi  {name}",
"sao mày sủa chậm dị?  {name}",
"nào làm lại tao nói đê?  {name}",
"bị tao chọc cay hơn con chó luôn😏  {name}",
"sủa đi rồi tao tha?  {name}",
"sủa điên lên cho mẹ?  {name}",
"mày ngưng là con đĩ mẹ mày chết?  {name}",
"cay tao lòi dái hả😏  {name}",
"não chó cay à?🤣  {name}",
"sao mày thảm dị=)))  {name}",
"mẹ mày bị tao địt rách màn trinh mà🤪  {name}",
"mẹ mày bị tao dã vào lồn=)))  {name}",
"địt mẹ mày sướng tê con cặc=)))  {name}",
"huhu nhìn mày như con cặc=)))  {name}",
"mày loạn luân bà già hả=)))  {name}",
"mẹ mày bị tao địt rên ư ử=)))  {name}",
"địt mẹ mày sảng khoái quá đi😛  {name}",
"tao địt mẹ mày nát lồn mà=)))  {name}",
"Ê bóng lồn  {name}",
"mẹ mày bị tao cưỡng hiếp=)))  {name}",
"mẹ mày đưa lồn chó liếm à🤣👈  {name}",
"mày óc cái lồn mà  {name}",
"năn nỉ đi tao tha😏  {name}",
"bú lồn tao đi🤪  {name}",
"mày ẳng gì dị?😏  {name}",
"nghe nói mày sợ tao?  {name}",
"thằng bê đê bất lực vì mẹ nó bị đụ tung cái lồn:)))  {name}",
"con đĩ mẹ mày bất lực vì bị tao chửi mà chỉ biết câm lặng:)))  {name}",
"làm màu mà bị tao chửi rung cái con cặc:)))  {name}",
"Mẹ mày bị tao đụ lòi hột le:)))  {name}",
"thằng bê đê ảo cặc đòi cân và cái kết:)))  {name}",
"con đĩ mẹ của mày thèm cứt tao dữ lắm:)))  {name}",
"bị tao chửi sảng cặc đéo dám care:)))  {name}",
"mạnh lên sao yếu đuối v con:)))  {name}",
"mày run cặc chưa con:)))  {name}",
"chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))  {name}",
"chết cha nó sồn r  {name}",
"con đĩ mẹ mày gào thét đê?😛  {name}",
"mày gào lên con?😏  {name}",
"sao cay tao dọ?  {name}",
"mày sủa đi nè😛  {name}",
"sao mày xấu lồn gớm chó dị con?  {name}",
"sao cay tao hả😏?  {name}",
"sao mày giết mẹ vậy=)))  {name}",
"mày gào đi con=)))  {name}",
"nào ổn thì đú🤣👈  {name}",
"ê bê đê lên ăn hôi lẹ😘  {name}",
"mày đú rõ mò  {name}",
"sao mày ăn cứt tao😏  {name}",
"ai cho mày ăn cứt tao  {name}",
"sao mày óc cặc dữ con=)))  {name}",
"gặp tao đừng run nha?😂  {name}",
"con đĩ mẹ mày thèm cứt tao dữ lắm=)))  {name}",
"mày mồ côi mà đúng k🤣👈  {name}",
"ai cho mày sủa tao cho mày sủa chưa?  {name}",
"bị tao chọc cay hơn con chó luôn=)))  {name}",
"cố đi sắp win rồi nè😏  {name}",
"chừng nào mày mới làm lại tao dị?  {name}",
"mẹ mày sắp tắt thở kìa ê  {name}",
"đậu má mày gà mà sủa  {name}",
  "cay {name}",
"kia {name}",
"c🤣👌{name}",
"oc {name}",
"cho {name}",
"di🤣🤣 {name}",
"me {name}",
"may {name}",
"ngu {name}",
"kia🐶 {name}",
"sao😏 {name}",
"yếu {name}",
"con{name}",
"on {name}",
"hong:))) {name}",
"🤣🤣 {name}",
"cay{name}",
"ko  {name}",
"cay tuột buồi 👉🤣{name}",
"ei ei =)) {name}",
"em {name}",
"chạy {name}",
"sợ 🤢🤢 {name}",
"kìa🤣🤣 👌{name}",
"bá{name}",
"dữ {name}",
"sua mau{name}",
"hú  {name}",
"kkk {name}",
"🤣🤣🐶 {name}",
"mau:)) {name}",
"đê :))) {name}",
"sủa mau=)) {name}",
":)) {name}",
"cố đi :3 {name}",
"sao:))) {name}",
"sua 🤣🤣 {name}",
"to 🤢🤢 {name}",
"len {name}",
" ui🤣🤣 {name}",
"kkk {name}",
"🤣🐶👌 {name}",
"oc 🤣🤣 {name}",
"kia {name}",
"may:)) {name}",
"đú :))) {name}",
"eo oyyy:3 {name}",
"cố {name}",
"lên)) {name}",
"cave 🤣🤣 {name}",
"mạnh lên:))) {name}",
"gõ loạn kìa {name}",
"thấy ngại ngùng z🤣🤘 {name}",
"tự nhiên đê {name}",
"mệt đk {name}",
"cấm m ngưng {name}",
"cay kia :))) {name}",
"lẹ đê:)) {name}",
"mày lag à :)) {name}",
"ngu:))) {name}",
"sua {name}",
"le {name}",
"con{name}",
"ey {name}",
"di{name}",
":))) {name}",
"me :))) {name}",
"may:))) {name}",
"sao chậm chạp v :)) {name}",
"óc 🤣🤣 {name}",
"lồn 🤣🤣 {name}",
"lên đê 🤣🤣 {name}",
"khựng dạ :))) {name}",
"t mạnh lắm à :))) {name}",
"chó ngu {name} ",
"bất ổn à 🤮🤮 {name}",
"run à {name}",
"chạy à  {name}",
"đuối à  {name}",
"bại chưa 👉😏 {name}",
"sủa mau🙄🙄👈 {name}",
  "Cha win à anh em😋🫰 {name}",
  " win r pp anh em🫰{name}",
  "cha trùm mxh {name}",
  "thằng bướm cay 🌶{name}",
"ớt cha lắm rồi đúng k {name}",
  "sủa cháy đê",
"sủa mạnh eei",
  "thẩm du cái lồn má m lên :))",
  "con đĩ cãi cùn",
  "địt bà nội sư gia nhà m =))",
  "úi úi",
  "nhanh lên con chó lồn khai khắm=))",
  "sao con đĩ mẹ ày gà vậy",
  "địt lồn mẹ mày",
  "dập cặc thằng cha mày liền",
  "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
  "Con thú đú",
  "lòi lồn chiến sĩ rồi à",
  "sao không mạnh mẽ lên",
  "khép lép vậy",
  "sợ hãi rồi à",
  "Lẹ lên con điếm thúi",
  "con đĩ mồ coi ăn hôi",
  "thế nào rồi",
  "sợ anh mày chưa",
  "anh mày bá sàn mà",
  "sao m chối hoài",
  "chối là con má m die",
  "ngu thì ngu vừa thôi=))",
  "không t đâm chết thằng cha mày",
  "óc chó dữ",
  "lồn mẹ mày",
  "điếm thúi ơi=))",
  "đừng rớt nhây nhó:3",
  "thấy sao rùi:3",
  "Bede sủa tiếng nghe choiw",
"run ớn dạ :))) {name}",
"óc đú 🤣🤣 {name}",
"rồi xong 🤢🤢 {name}",
"có thể hăng ko á  {name}",
"ẻm cay doài =))) {name}",
"cay tuột buồi 👉🤣{name}",
"ei ei =)) {name}",
"em ei :3 {name}",
"chạy à {name}",
"mày sợ hả 🤢🤢 {name}",
"coi ẻm sồn kìa🤣🤣 👌{name}",
"lại bá à :))) {name}",
"sao chậm dữ {name}",
"eo oyyy:3 {name}",
"hú hú🤨 {name}",
"sao ức chế dạ 😏😏 {name}",
"con não cún bị chửi kìa 🤣🤣🐶 {name}",
"mau đê :)) {name}",
"hăng đê :))) {name}",
"sủa mau đê =)) {name}",
"cần cứu ko :)) {name}",
"cố đi :3 {name}",
"gáng lên đê :))) {name}",
"sủa to lên🤣🤣 {name}",
"phò nông thôn 🤢🤢 {name}",
"óc cặc tỉnh lẽ =)))) {name}",
"khoẻ ko 🤣🤣 {name}",
"kkk {name}",
"đói à🤣🐶👌 {name}",
"ăn chưa à 🤣🤣 {name}",
"chưa đk :))) {name}",
"thấy kém cõi :)) {name}",
"đú cứt kìa :))) {name}",
"eo oyyy:3 {name}",
"cố đê 🤣🤣 {name}",
"thấy mày đơ đơ :))) {name}",
"con cave 🤣🤣 {name}",
"mạnh lên:))) {name}",
"gõ mạnh lên đê:)) {name}",
"thấy ngại ngùng z🤣🤘 {name}",
"tự nhiên đê {name}",
"mệt đk {name}",
"cấm m ngưng {name}",
"đĩ đầu đinh :))) {name}",
"lẹ đê:)) {name}",
"mày lag à :)) {name}",
"m trầm cảm à :))) {name}",
"tâm lí ko vững à :)) {name}",
"cần thuốc à :)) {name}",
"hấp hối hả🤣🤣 {name}",
"khó thở dk :)) {name}",
"cần oxi ko :))) {name}",
"mày bệnh nặng lắm à :))) {name}",
"tuột hứng cha :))) {name}",
"tnh gà :))) {name}",
"sao chậm chạp v :)) {name}",
"óc dái 🤣🤣 {name}",
"lồn cụ con đĩ đớ🤣🤣 {name}",
"lưu loát lên đê 🤣🤣 {name}",
"khựng dạ :))) {name}",
"t mạnh lắm phải ko à :))) {name}",
":))) nhỏ mếu à ae {name}",
"m nghèo mà {name}",
"sợ t lắm à:3 {name}",
"hả cu =))) {name}",
"thấy tội quá:)) {name}",
"thương ẻm cố gắng🤢🤘 {name}",
"mà ngu🤣🤣 {name}",
":)) 🤣🤣 {name}",
"cay lắm à :)) {name}",
"nhạt nhoè v à {name}",
"ko cảm hứng để hăng à :))) {name}",
"xạo lồn à :))) {name}",
"khóc đk :))) {name}",
"cave tỉnh lẽ phát biểu:)) {name}",
"ra tín hiệu đê :))) {name}",
"SOS con dái đú 🤣🤣🤢 {name}",
"ớ ớ ớ :))) {name}",
"chó ăn cứt :))) {name}",
"chó đú sàn 👌🐶 {name}",
"ỉa ra máu r à :))) {name}",
"nghèo k có nghi lực à:)) {name}",
"phản kháng đê :))) t win à {name}",
"kkk {name}",
"m chết r à :))) {name}",
"m nghèo mà em 😏🤣 {name}",
"m thèm cứt t mà:)) {name}",
"đĩ mẹ m ngu mà👉🤣 {name}",
"m cay tao mà :)) {name}",
"con óc cứt thối🤢🤢 {name}",
"con đĩ mặt chim🤪🤪 {name}",
"ôm hận à 🤨 {name}",
"con đĩ nhà núi :))) {name}",
"bede bóng lộ =)) {name}",
"cn đĩ mẹ mày {name}",
"tao từ hình mẹ m mà :)) {name}",
"tk phế vật ăn hại😏🤘 {name}",
"đú đởn hả con :)) {name}",
"m sao dọ {name}",
"sủa nè  {name}",
"123 sủa😏 {name}",
"lẹ nè  {name}",
"alo alo hú hú  {name}",
"th cầm thú {name}",
"m s dạ  {name}",
"m sợ mẹ hả  {name}",
"lên đi mẹ ko giết cha má m đâu mà 😏 {name}",
"hù :)) {name}",
"bất ổn hở {name}",
"s đó  {name}",
"m rớt kìa th gà🤪 {name}",
"t cấm m chối nhen {name}",
"chối t giết cha má m nè:))) {name}",
"hăng xíu lẹ kaka🤢 {name}",
"th đần  {name}",
"lên mẹ biểu {name}",
"k lên t tuyệt chủng m nhen cn thú {name}",
"m thích đú ko dạ🤨 {name}",
"ko rep = t win nhen  {name}",
"cấm chạy nhen {name}",
"m mau  {name}",
"lên đây ơ ơ  {name}",
"th ngu ê {name}",
"s á lên đây mẹ sút m chết {name}",
"m khóc à 👉🤣 {name}",
"sủa liên tục ơ🤣🤣 {name}",
"cầu cứu lũ đú à  {name}",
"sục dái nó xem à {name}",
"dái thâm v? {name}",
"chậm v cn culi🤣🤣👌 {name}",
"hoảng loạn à {name}",
"bất ổn à 🤮🤮 {name}",
"run à {name}",
"chạy à  {name}",
"đuối à  {name}",
"bại chưa 👉😏 {name}",
"sủa mau🙄🙄👈 {name}",
"mạnh dạn lên  {name}",
"nhanh t cho cơ hội cứu má m nè {name}",
"cấm mách mẹ {name}",
"ảo war hở :)) {name}",
"dồn ko  {name}",
"đua nè lên sàn t chấp😏👌 {name}",
"th chợ búa m sao v {name}",
"th đầu buồi mặt chó😢🫵🏻👈🏻 {name}",
"cấm hoảng loạn {name}",
"lại phải win nữa à🙄🙄 {name}",
"kkk {name}",
	"chó ăn cứt 🤣🤣 {name}",
"sủa đê 🤣🤣 {name}",
"chó bú cứt🤣🤣👌{name}",
"hăng hái đê :)) {name}",
"chậm dọ 🤣🤣 {name}",
"óc dái cay rồi🤣🤣 {name}",
"ăn hại phát biểu lẹ đê 🤣🤣 {name}",
"óc dái + óc lồn :))) {name}",
"ổn phải k? {name}",
"ngu ớn 🤣🤣👌 {name}",
"chó ăn cứt 🐶 {name}",
"thằng dái đú :)))) {name}",
"yếu dữ ta😏😏 {name}",
"con chó đần👉🤣 {name}",
"ổn dữ chưa =))) {name}",
"run ớn dạ :))) {name}",
"óc đú 🤣🤣 {name}",
"rồi xong 🤢🤢 {name}",
"có thể hăng ko á  {name}",
"ẻm cay doài =))) {name}",
"cay tuột buồi 👉🤣{name}",
"ei ei =)) {name}",
"em ei :3 {name}",
"chạy à {name}",
"mày sợ hả 🤢🤢 {name}",
"coi ẻm sồn kìa🤣🤣 👌{name}",
"lại bá à :))) {name}",
"sao chậm dữ {name}",
"eo oyyy:3 {name}",
"hú hú🤨 {name}",
"sao ức chế dạ 😏😏 {name}",
"con não cún bị chửi kìa 🤣🤣🐶 {name}",
"mau đê :)) {name}",
"hăng đê :))) {name}",
"sủa mau đê =)) {name}",
"cần cứu ko :)) {name}",
"cố đi :3 {name}",
"gáng lên đê :))) {name}",
"sủa to lên🤣🤣 {name}",
"phò nông thôn 🤢🤢 {name}",
"óc cặc tỉnh lẽ =)))) {name}",
"khoẻ ko 🤣🤣 {name}",
"kkk {name}",
"đói à🤣🐶👌 {name}",
"ăn chưa à 🤣🤣 {name}",
"chưa đk :))) {name}",
"thấy kém cõi :)) {name}",
"đú cứt kìa :))) {name}",
"eo oyyy:3 {name}",
"cố đê 🤣🤣 {name}",
"thấy mày đơ đơ :))) {name}",
"con cave 🤣🤣 {name}",
"mạnh lên:))) {name}",
"gõ mạnh lên đê:)) {name}",
"thấy ngại ngùng z🤣🤘 {name}",
"tự nhiên đê {name}",
"mệt đk {name}",
"cấm m ngưng {name}",
"đĩ đầu đinh :))) {name}",
"lẹ đê:)) {name}",
"mày lag à :)) {name}",
"m trầm cảm à :))) {name}",
"tâm lí ko vững à :)) {name}",
"cần thuốc à :)) {name}",
"hấp hối hả🤣🤣 {name}",
"khó thở dk :)) {name}",
"cần oxi ko :))) {name}",
"mày bệnh nặng lắm à :))) {name}",
"tuột hứng cha :))) {name}",
"tnh gà :))) {name}",
"sao chậm chạp v :)) {name}",
"óc dái 🤣🤣 {name}",
"lồn cụ con đĩ đớ🤣🤣 {name}",
"lưu loát lên đê 🤣🤣 {name}",
"khựng dạ :))) {name}",
"t mạnh lắm phải ko à :))) {name}",
":))) nhỏ mếu à ae {name}",
"m nghèo mà {name}",
"sợ t lắm à:3 {name}",
"hả cu =))) {name}",
"thấy tội quá:)) {name}",
"thương ẻm cố gắng🤢🤘 {name}",
"mà ngu🤣🤣 {name}",
":)) 🤣🤣 {name}",
"cay lắm à :)) {name}",
"nhạt nhoè v à {name}",
"ko cảm hứng để hăng à :))) {name}",
"xạo lồn à :))) {name}",
"khóc đk :))) {name}",
"cave tỉnh lẽ phát biểu:)) {name}",
"ra tín hiệu đê :))) {name}",
"SOS con dái đú 🤣🤣🤢 {name}",
"ớ ớ ớ :))) {name}",
"chó ăn cứt :))) {name}",
"chó đú sàn 👌🐶 {name}",
"ỉa ra máu r à :))) {name}",
"nghèo k có nghi lực à:)) {name}",
"phản kháng đê :))) t win à {name}",
"kkk {name}",
"m chết r à :))) {name}",
"m nghèo mà em 😏🤣 {name}",
"m thèm cứt t mà:)) {name}",
"đĩ mẹ m ngu mà👉🤣 {name}",
"m cay tao mà :)) {name}",
"con óc cứt thối🤢🤢 {name}",
"con đĩ mặt chim🤪🤪 {name}",
"ôm hận à 🤨 {name}",
"con đĩ nhà núi :))) {name}",
"bede bóng lộ =)) {name}",
"cn đĩ mẹ mày {name}",
"tao từ hình mẹ m mà :)) {name}",
"tk phế vật ăn hại😏🤘 {name}",
"đú đởn hả con :)) {name}",
"m sao dọ {name}",
"sủa nè  {name}",
"123 sủa😏 {name}",
"lẹ nè  {name}",
"alo alo hú hú  {name}",
"th cầm thú {name}",
"m s dạ  {name}",
"m sợ mẹ hả  {name}",
"lên đi mẹ ko giết cha má m đâu mà 😏 {name}",
"hù :)) {name}",
"bất ổn hở {name}",
"s đó  {name}",
"m rớt kìa th gà🤪 {name}",
"t cấm m chối nhen {name}",
"chối t giết cha má m nè:))) {name}",
"hăng xíu lẹ kaka🤢 {name}",
"th đần  {name}",
"lên mẹ biểu {name}",
"k lên t tuyệt chủng m nhen cn thú {name}",
"m thích đú ko dạ🤨 {name}",
"ko rep = t win nhen  {name}",
"cấm chạy nhen {name}",
"m mau  {name}",
"lên đây ơ ơ  {name}",
"th ngu ê {name}",
"s á lên đây mẹ sút m chết {name}",
"m khóc à 👉🤣 {name}",
"sủa liên tục ơ🤣🤣 {name}",
"cầu cứu lũ đú à  {name}",
"sục dái nó xem à {name}",
"dái thâm v? {name}",
"chậm v cn culi🤣🤣👌 {name}",
"hoảng loạn à {name}",
"bất ổn à 🤮🤮 {name}",
"run à {name}",
"chạy à  {name}",
"đuối à  {name}",
"bại chưa 👉😏 {name}",
"sủa mau🙄🙄👈 {name}",
"mạnh dạn lên  {name}",
"nhanh t cho cơ hội cứu má m nè {name}",
"cấm mách mẹ {name}",
"ảo war hở :)) {name}",
"dồn ko  {name}",
"đua nè lên sàn t chấp😏👌 {name}",
"th chợ búa m sao v {name}",
"th đầu buồi mặt chó😢🫵🏻👈🏻 {name}",
"cấm hoảng loạn {name}",
"lại phải win nữa à🙄🙄 {name}",
"nhìn mày gõ tao thấy tội dùm {name}",
  "anh bá mà phải không🙄🙄 {name}",
  "anh trùm con mẹ nó rồi 🤣 {name}",
  "cay cha lắm đúng không 🤣👈 {name}",
  "mày ngu nên cay cha là đúng {name}",
  "gõ chậm quá thằng nhóc 😜🐶 {name}",
  "nào nhanh nói cha nha 🤣🤣 {name}",
  "nhìn mày gõ phèn vcl 😏 {name}",
  "thằng cặc đang vang xin anh tha {name}",
  "thằng đĩ lồn {name}",
"Thằng Óc Cặc {name}",
  "cay cha à  {name}",
  "nhìn mặt mày đỏ như đít khỉ kìa🤣 {name}",
  "nhìn mày hài vc {name}",
  "làm trò hề cho ai xem vậy  {name}",
  "Thằng Nghịch Tử  {name}",
  "Thằng Đĩ Lồn  {name}",
  "Bị Chó tao cắn cho gãy cặc  {name}",
  "đời mày coi như xong  {name}",
  "nhìn mày nghịch tử loạn luân  {name}",
  "tao buồn hộ dùm ông bà già mày  {name}",
  "Thằng Cặc Bị Tao Sút Cho Chết  {name}",
  "Lại Bá À 🤣🤣🤣  {name}",
  "Anh xin cái win nhé thằng ngu  {name}",
  "đĩ mẹ mày đang cay anh kìa  {name}",
  "chó ăn cứt cay 🤣🤣 {name}",
"sủa đê 🤣🤣 {name}",
"chó bú cứt🤣🤣👌{name}",
"hăng hái đê :)) {name}",
"chậm dọ 🤣🤣 {name}",
"óc dái cay rồi🤣🤣 {name}",
"ăn hại phát biểu lẹ đê 🤣🤣 {name}",
"óc dái + óc lồn :))) {name}",
"ổn phải k? {name}",
"ngu ớn 🤣🤣👌 {name}",
"chó ăn cứt 🐶 {name}",
"thằng dái đú :)))) {name}",
"yếu dữ ta😏😏 {name}",
"con chó đần👉🤣 {name}",
"ổn dữ chưa =))) {name}",
  "sồn hả",
"run ớn dạ :))) {name}",
  "sợ cha rõ",
"óc đú 🤣🤣 {name}",
"rồi xong 🤢🤢 {name}",
  "nó treo cổ tự tử kìa",
"có thể hăng ko á  {name}",
  "sồn như chó",
"ẻm cay doài =))) {name}",
"cay tuột buồi 👉🤣{name}",
"ei ơi từ bỏ đi =)) {name}",
"em ei :3 {name}",
"chạy à {name}",
"mày sợ hả 🤢🤢 {name}",
"coi ẻm sồn kìa🤣🤣 👌{name}",
"lại bá à :))) {name}",
"sao chậm dữ {name}",
"eo oyyy con gà:3 {name}",
  "thằng bê đê bất lực vì mẹ nó bị đụ tung cái lồn:)))  {name}",
"con đĩ mẹ mày bất lực vì bị tao chửi mà chỉ biết câm lặng:)))  {name}",
"làm màu mà bị tao chửi rung cái con cặc:)))  {name}",
"Mẹ mày bị tao đụ lòi hột le:)))  {name}",
"thằng bê đê ảo cặc đòi cân và cái kết:)))  {name}",
"con đĩ mẹ của mày thèm cứt tao dữ lắm:)))  {name}",
"bị tao chửi sảng cặc đéo dám care:)))  {name}",
"mạnh lên sao yếu đuối v con:)))  {name}",
"mày run cặc chưa con:)))  {name}",
"chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))  {name}",
"chết cha nó sồn r  {name}",
"con đĩ mẹ mày gào thét đê?😛  {name}",
"mày gào lên con?😏  {name}",
"sao cay tao dọ?  {name}",
"mày sủa đi nè😛  {name}",
"sao mày xấu lồn gớm chó dị con?  {name}",
"sao cay tao hả😏?  {name}",
"sao mày giết mẹ vậy=)))  {name}",
"mày gào đi con=)))  {name}",
"nào ổn thì đú🤣👈  {name}",
"ê bê đê lên ăn hôi lẹ😘  {name}",
"mày đú rõ mò  {name}",
"sao mày ăn cứt tao😏  {name}",
"ai cho mày ăn cứt tao  {name}",
"sao mày óc cặc dữ con=)))  {name}",
"gặp tao đừng run nha?😂  {name}",
"con đĩ mẹ mày thèm cứt tao dữ lắm=)))  {name}",
"mày mồ côi mà đúng k🤣👈  {name}",
"ai cho mày sủa tao cho mày sủa chưa?  {name}",
"bị tao chọc cay hơn con chó luôn=)))  {name}",
"cố đi sắp win rồi nè😏  {name}",
"chừng nào mày mới làm lại tao dị?  {name}",
"mẹ mày sắp tắt thở kìa ê  {name}",
"đậu má mày gà mà sủa  {name}",
"sủa điên đi mà sủa hăng lên mới vui😘  {name}",
"mày mà ngưng một giây là con đĩ mẹ mày bả tắt đường thở á😏  {name}",
"ê chó ngu mày sợ tao hả😂  {name}",
"mày đú rõ mà sao mày đú dị?  {name}",
"mẹ mày chết chưa con=)))  {name}",
"ê bê đê sủa điên đi  {name}",
"sao mày sủa chậm dị?  {name}",
"nào làm lại tao nói đê?  {name}",
"bị tao chọc cay hơn con chó luôn😏  {name}",
"sủa đi rồi tao tha?  {name}",
"sủa điên lên cho mẹ?  {name}",
"mày ngưng là con đĩ mẹ mày chết?  {name}",
"cay tao lòi dái hả😏  {name}",
"não chó cay à?🤣  {name}",
"sao mày thảm dị=)))  {name}",
"mẹ mày bị tao địt rách màn trinh mà🤪  {name}",
"mẹ mày bị tao dã vào lồn=)))  {name}",
"địt mẹ mày sướng tê con cặc=)))  {name}",
"huhu nhìn mày như con cặc=)))  {name}",
"mày loạn luân bà già hả=)))  {name}",
"mẹ mày bị tao địt rên ư ử=)))  {name}",
"địt mẹ mày sảng khoái quá đi😛  {name}",
"tao địt mẹ mày nát lồn mà=)))  {name}",
"Ê bóng lồn  {name}",
"mẹ mày bị tao cưỡng hiếp=)))  {name}",
"mẹ mày đưa lồn chó liếm à🤣👈  {name}",
"mày óc cái lồn mà  {name}",
"năn nỉ đi tao tha😏  {name}",
"bú lồn tao đi🤪  {name}",
"mày ẳng gì dị?😏  {name}",
"nghe nói mày sợ tao?  {name}",
"vô danh cấm sủa?😏  {name}",
"gì mày thèm cứt tao hả=)))?  {name}",
"sao mày lề mề dị con  {name}",
"mày có tuổi hở?😏  {name}",
"tuổi lồn ăn tao á😏?  {name}",
"tao đụ má mày ná thở mà😛 {name}",
"hú hú🤨 {name}",
"sao ức chế dạ 😏😏 {name}",
"con não cún bị chửi kìa 🤣🤣🐶 {name}",
"mau đê :)) {name}",
"hăng đê :))) {name}",
"sủa mau đê =)) {name}",
"cần cứu ko :)) {name}",
"cố đi :3 {name}",
"gáng lên đê :))) {name}",
"sủa to lên🤣🤣 {name}",
"phò nông thôn 🤢🤢 {name}",
"óc cặc tỉnh lẽ =)))) {name}",
"khoẻ ko 🤣🤣 {name}",
"kkk {name}",
"đói à🤣🐶👌 {name}",
  "thèm nước lồn đến điên à 🤣 {name}",
 "nhìn mày phát điên vì thiếu lồn {name}",
   "óc lồn  {name}",
   "óc cặc zô zô chửi anh đi  {name}",
   "súc vật 4 chân à 🤣😜 {name}",
   "đói như con chó  {name}",
   "nhìn hài vc  {name}",
   "nhìn mày tật vc 🤣  {name}",
   "cố lên sắp ngầu rồi  {name}",
   "thằng rác 🤣👉 {name}",
   "nghịch tử 👉  {name}",
   "ngu còn tật 🤣👉  {name}",
   "ảo mxh tao hết cú👉 {name}",
   "gõ nhanh lên tao xem nào 😜🤣  {name}",
   "cay cha à thằng ngu 👉  {name}",
   "nhìn mày hề vc  {name}",
   "Hăng đi con chó  {name}",
   "Hăng Lên Đi Con Chó Ngu  {name}",
   "cạn ngôn à tao biết mà  {name}",
   "Sao Câm Rồi Bí Ngôn À  {name}",
   "Cãi Tao = Mày Ngu  {name}",
   "Câm = Mày Ngu  {name}",
 "sao em ngu vậy  {name}",
   "nào mới hết ngu vậy  {name}",
   "Con Chó Ngu Sủa Cha Nghe  {name}",
  "mau đê :)) {name}",
"hăng đê :))) {name}",
"sủa mau đê =)) {name}",
"cần cứu ko :)) {name}",
"cố đi :3 {name}",
"gáng lên đê :))) {name}",
"sủa to lên🤣🤣 {name}",
"phò nông thôn 🤢🤢 {name}",
"óc cặc tỉnh lẽ =)))) {name}",
"khoẻ ko 🤣🤣 {name}",
"kkk {name}",
"đói à🤣🐶👌 {name}",
  "sồn đi con thú",
"con đĩ mẹ mày hài",




  



  
"kkk {name}"
]; // các câu chửi, thêm {name} để thay thế bằng tên người bị chửi và đồng thời tag người đó

async function onCall({ message, args }) {
	const { mentions } = message;
	const mentionId = Object.keys(mentions)[0];
	const mentionName = mentions[mentionId];

	const isCallingStop = args[0]?.toLowerCase() === 's';

	if (!mentionId && !isCallingStop) return message.reply("mày óc dái à");
	if (isCallingStop) {
		if (!global.chuilientuc.has(message.threadID)) return message.reply("Bot không đang chửi ai cả");
		global.chuilientuc.delete(message.threadID);
		return message.reply("Óc Dái");
	}


	const _d = global.chuilientuc.get(message.threadID);

	if (_d) {
		const now = Date.now();
		const time = _d.time;
		const diff = now - time;

		if (diff < DELAY_THREAD) {
			const timeLeft = (DELAY_THREAD - diff) / 2400;
			return message.reply(`Vui lòng đợi ${Math.ceil(timeLeft)}s để tiếp tục chửi`);
		}
	}
	
	global.chuilientuc.set(message.threadID, {
		time: Date.now()
	});


	for (let i = 0; i < CAU_CHUI.length; i++) {
		if (!global.chuilientuc.has(message.threadID)) return;
		const cauChui = CAU_CHUI[i];
		
		if (cauChui.includes('{name}')) {
			const cauChuiFinal = cauChui.replace('{name}', mentionName);

			await message.send({
				body: cauChuiFinal,
				mentions: [{
					tag: mentionName,
					id: mentionId
				}]
			});
		} else {
			await message.send(cauChui);
		}

		await new Promise(resolve => setTimeout(resolve, DELAY));
	}
}


export default {
		config,
		onCall
}
